-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Dec 20, 2023 at 11:01 AM
-- Server version: 10.6.15-MariaDB-cll-lve
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u765928901_past_questions`
--

-- --------------------------------------------------------

--
-- Table structure for table `admins`
--

CREATE TABLE `admins` (
  `id` int(255) NOT NULL,
  `name` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `practice_questions`
--

CREATE TABLE `practice_questions` (
  `id` int(11) NOT NULL,
  `course_name` varchar(250) NOT NULL,
  `question` varchar(2550) NOT NULL,
  `optionA` varchar(250) NOT NULL,
  `optionB` varchar(250) NOT NULL,
  `optionC` varchar(250) NOT NULL,
  `optionD` varchar(250) NOT NULL,
  `answer` varchar(250) NOT NULL,
  `explaination` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `practice_questions`
--

INSERT INTO `practice_questions` (`id`, `course_name`, `question`, `optionA`, `optionB`, `optionC`, `optionD`, `answer`, `explaination`) VALUES
(1, 'java', '1. Who invented Java Programming?', 'Guido van Rossum', 'James Gosling', 'Dennis Ritchie', 'Bjarne Stroustrup', 'B', 'Java programming was developed by James Gosling at Sun Microsystems in 1995. James Gosling is well known as the father of Java.'),
(2, 'java', 'Which statement is true about Java?', ' Java is a sequence-dependent programming language', ' Java is a code dependent programming language', ' Java is a platform-dependent programming language', 'Java is a platform-independent programming language', 'D', 'Java is called ‘Platform Independent Language’ as it primarily works on the principle of ‘compile once, run everywhere’.'),
(3, 'java', 'Which component is used to compile, debug and execute the java programs?', 'JRE', 'JIT', 'JDK', 'JVM', 'C', 'JDK is a core component of Java Environment and provides all the tools, executables and binaries required to compile, debug and execute a Java Program.'),
(4, 'java', 'Which one of the following is not a Java feature?', ' Object-oriented', ' Use of pointers', 'Portable', 'Dynamic and Extensible', 'B', 'Explanation: Pointers is not a Java feature. Java provides an efficient abstraction layer for developing without using a pointer in Java. Features of Java Programming are Portable, Architectural Neutral, Object-Oriented, Robust, Secure, Dynamic and E'),
(5, 'java', 'Which of these cannot be used for a variable name in Java?', ' identifier & keyword', 'identifier', 'keyword', 'none of the mentioned', 'C', ' Keywords are specially reserved words that can not be used for naming a user-defined variable, for example: class, int, for, etc.\r\n'),
(6, 'java', 'Which of the following option leads to the portability and security of Java?', 'Bytecode is executed by JVM', 'The applet makes the Java code secure and portable', 'Use of exception handling', 'Dynamic binding between objects', 'A', 'he output of the Java compiler is bytecode, which leads to the security and portability of the Java code. It is a highly developed set of instructions that are designed to be executed by the Java runtime system known as Java Virtual Machine (JVM). Th'),
(7, 'java', 'Which of the following is not a Java features?', 'Which of the following is not a Java features?', 'Architecture Neutral', 'Use of pointers', 'Object-oriented', 'C', 'The Java language does not support pointers; some of the major reasons are listed below:\r\n\r\nOne of the major factors of not using pointers in Java is security concerns. Due to pointers, most of the users consider C-language very confusing and complex'),
(8, 'java', 'What should be the execution order, if a class has a method, static block, instance block, and constructor, as shown below?\r\n\r\npublic class First_C {  <br>\r\n      public void myMethod()   <br>\r\n    {  <br>\r\n    System.out.println(\"Method\");  <br>\r\n    }  <br>\r\n      \r\n    {  <br>\r\n    System.out.println(\" Instance Block\");  <br>\r\n    }  <br>\r\n          \r\n    public void First_C()  <br>\r\n    {  <br>\r\n    System.out.println(\"Constructor \");  <br>\r\n    }  <br>\r\n    static {  <br>\r\n        System.out.println(\"static block\");  <br>\r\n    }  <br>\r\n    public static void main(String[] args) {  <br>\r\n    First_C c = new First_C();  <br>\r\n    c.First_C();  <br>\r\n    c.myMethod();  <br>\r\n  }  <br>\r\n}   <br>', 'Instance block, method, static block, and constructor', 'Method, constructor, instance block, and static block', 'Static block, method, instance block, and constructor', 'Static block, instance block, constructor, and method', 'D', 'The static block will execute whenever the class is loaded by JVM.\r\nInstance block will execute whenever an object is created, and they are invoked before the constructors. For example, if there are two objects, the instance block will execute two ti'),
(9, 'java', 'What will be the output of the following program?<br>\r\npublic class MyFirst {  <br>\r\n      public static void main(String[] args) {  <br>\r\n         MyFirst obj = new MyFirst(n);  <br>\r\n }  <br>\r\n static int a = 10;  <br>\r\n static int n;  <br>\r\n int b = 5;  <br>\r\n int c;  <br>\r\n public MyFirst(int m) {  <br>\r\n       System.out.println(a + \", \" + b + \", \" + c + \", \" + n + \", \" + m);  <br>\r\n   }  <br>\r\n// Instance Block  <br>\r\n  {  <br>\r\n     b = 30;  <br>\r\n     n = 20;  <br>\r\n  }   <br>\r\n// Static Block  <br>\r\n  static   <br>\r\n{  <br>\r\n          a = 60;  <br>\r\n     }   <br>\r\n }  <br>', '10, 5, 0, 20, 0', '10, 30, 20', '60, 5, 0, 20', '60, 30, 0, 20, 0', 'D', 'In the above code, there are two values of variable a, i.e., 10 and 60. Similarly, there are two values of variable b, i.e., 5 and 30. But in the output, the values of a and b are 60 and 30, respectively. It is because of the execution order of the p'),
(10, 'java', 'The u0021 article referred to as a', 'Unicode escape sequence', 'Octal escape', 'Hexadecimal', 'Line feed', 'A', 'In Java, Unicode characters can be used in string literals, comments, and commands, and are expressed by Unicode Escape Sequences. A Unicode escape sequence is made up of the following articles:\r\n\r\nA backslash \"\" (ASCII character 92)\r\nA \"u\" (ASCII 11'),
(16, 'java', ' _____ is used to find and fix bugs in the Java programs.', 'JVM', 'JRE', 'JDK', 'JDB', 'D', 'The Java Debugger (JDB or jdb) is a command-line java debugger that debugs the java class. It is a part of the Java Platform Debugger Architecture (JPDA) that helps in the inspections and debugging of a local or remote Java Virtual Machine (JVM).\r\n\r\n'),
(17, 'java', 'Which of the following is a valid declaration of a char?', 'char ch = \"utea\";', 'char ca = \"tea\";', 'char cr = u0223;', 'char cc = \"itea\";', 'A', 'A char literal may contain a Unicode character (UTF-16). We can directly use these characters only if our file system allows us, else use a Unicode escape (u) such as \"u02tee\". The char literals are always declared in single quotes (\").\r\n\r\nThe option'),
(18, 'java', 'What is the return type of the hashCode() method in the Object class?', 'Object', 'int', 'long', 'void', 'B', 'In Java, the return type of hashCode() method is an integer, as it returns a hash code value for the object.'),
(19, 'java', 'Which of the following is a valid long literal?', 'ABH8097', 'L990023', '904423', '0xnf029L', 'D', 'For every long literal to be recognized by Java, we need to add L character at the end of the expression. It can be either uppercase (L) or lowercase (l) character. However, it is recommended to use uppercase character instead of lowercase because th'),
(20, 'java', 'What does the expression float a = 35 / 0 return?', '0', 'Not a Number', 'Infinity', 'Run time exception', 'C', 'In Java, whenever we divide any number (double, float, and long except integer) by zero, it results in infinity. According to the IEEE Standard for Floating-Point Arithmetic (IEEE 754), if we divide 1/0 will give positive infinity, -1/0 will give neg'),
(21, 'java', 'Evaluate the following Java expression, if x=3, y=5, and z=10:\r\nEvaluate the following Java expression, if x=3, y=5, and z=10:', '24', '23', '20', '25', 'D', 'In the above expression, ++z means that the value will first increment by 1, i.e. 12. Now, evaluate the statement by putting the values of x, y, and z. On evaluating the expression, we get 25, as shown below.'),
(22, 'java', 'What will be the output of the following program?\r\npublic class Test {  \r\npublic static void main(String[] args) {  \r\n    int count = 1;  \r\n    while (count <= 15) {  \r\n    System.out.println(count % 2 == 1 ? \"***\" : \"+++++\");  \r\n    ++count;  \r\n        }      // end while  \r\n    }       // end main   \r\n }  \r\n', '15 times ***', '15 times +++++', '8 times *** and 7 times +++++', 'oth will print only once', 'C', 'In the above code, we have declared count = 1. The value of count will be increased till 14 because of the while (count<=15) statement. If the remainder is equal to 1 on dividing the count by 2, it will print (***) else print (+++++). Therefore, for '),
(23, 'java', 'Which of the following tool is used to generate API documentation in HTML format from doc comments in source code?', 'javap tool', 'javaw command', 'Javadoc tool', 'javah command', 'C', 'The Javadoc is a tool that is used to generate API documentation in HTML format from the Java source files. In other words, it is a program (tool) that reads a collection of source files into an internal form.\r\n\r\nThe Javadoc command line syntax is,\r\n'),
(24, 'java', 'Which of the following creates a List of 3 visible items and multiple selections abled?', 'new List(false, 3)', 'new List(3, true)', 'new List(true, 3)', 'new List(3, false)', 'B', 'From the above statements, the new List(3, true) is the correct answer; this is because of the constructor type. To create a list of 3 visible items along with the multiple selections abled, we have to use the following constructor of the List class.'),
(25, 'java', 'Which of the following for loop declaration is not valid?', 'for ( int i = 99; i >= 0; i / 9 )', 'for ( int i = 7; i <= 77; i += 7 )', 'for ( int i = 20; i >= 2; - -i )', 'for ( int i = 2; i <= 20; i = 2* i )', 'A', 'The first option is not a valid declaration as i/9 is not declared correctly. The correct statement will be:\r\n      for ( int i= 99; i>=0; i= i/9)\r\n\r\nThen the code would execute. But without assigning the value of i/9 to a variable, it would not exec'),
(26, 'java', 'Which method of the Class.class is used to determine the name of a class represented by the class object as a String?', 'getClass()', 'intern()', 'getName()', 'toString()', 'C', 'The getName() method of the Class class returns the name (as String) of the entity (class, interface) represented by this Class object. It is a non-static method, and available in the java.lang package.\r\n\r\nThe getClass() method of the Object class re'),
(27, 'java', 'In which process, a local variable has the same name as one of the instance variables?', 'Serialization', 'Variable Shadowing', 'Abstraction', 'Multi-threading', 'B', 'There are following reasons for considering a variable shadowing, they are listed below:\r\n\r\nWhen we define a variable in a local scope with a variable name same as the name of a variable defined in an instance scope.\r\nWhen a subclass declares a varia'),
(28, 'java', 'Which of the following is true about the anonymous inner class?', 'It has only methods', 'Objects can\"t be created', 'It has a fixed class name', 'It has a fixed class name', 'D', 'Anonymous inner classes are the same as the local classes except that they don\"t have any name. The main use of it is to override methods of classes or interfaces. And the rest three options are false about the anonymous inner classes as it can have '),
(29, 'java', 'Which package contains the Random class?', 'java.util package', 'java.lang package', 'java.awt package', 'jjava.awt package', 'A', 'The Random class is available in the java.util package. An object of the Random class is used to generate a series of pseudorandom numbers. And the object of this class is a thread-safe and cryptographically insecure object. The Random class provides'),
(30, 'java', 'What do you mean by nameless objects?', 'An object created by using the new keyword.', 'An object of a superclass created in the subclass.', 'An object without having any name but having a reference.', 'An object that has no reference.', 'D', 'The nameless objects are basically referred to as anonymous objects. The anonymous objects do not have any names. We can also say that, when an object is initialized but is not assigned to any reference variable, it is called an anonymous object. For'),
(31, 'java', ' An interface with no fields or methods is known as a ______', 'Runnable Interface', 'Marker Interface', 'Abstract Interface', 'CharSequence Interface', 'B', 'An interface with no methods and fields is known as the marker interface. In other words, an empty interface (containing no fields and methods) is called a marker interface. In Java, the most commonly used marker interfaces are Serializable, Cloneabl'),
(32, 'java', 'Which of the following is an immediate subclass of the Panel class?', 'Applet class', 'Window class', 'Frame class', 'Dialog class', 'A', 'According to the class hierarchy of Java Swing, the Applet class is the direct subclass of the Panel class. You can go through the link, (https://www.javatpoint.com/java-swing) to deeply understand the class hierarchy diagram. The Panel class and Win'),
(33, 'java', 'Which option is false about the final keyword?', 'A final method cannot be overridden in its subclasses.', 'A final class cannot be extended.', 'A final class cannot extend other classes.', 'A final method can be inherited.', 'A', 'The final is a reserved keyword in Java that is used to make a variable, method, and class immutable. The important features of the final keyword are:\r\n\r\nUsing the final keyword with a variable makes it constant or immutable. We can\"t reassign the va'),
(34, 'java', 'Which of these classes are the direct subclasses of the Throwable class?', 'RuntimeException and Error class', 'Exception and VirtualMachineError class', 'Error and Exception class', 'IOException and VirtualMachineError class', 'C', 'According to the class hierarchy of Throwable class, the Error and Exception classes are the direct subclasses of the Throwable class, '),
(35, 'java', 'What do you mean by chained exceptions in Java?', 'Exceptions occurred by the VirtualMachineError', 'An exception caused by other exceptions', 'Exceptions occur in chains with discarding the debugging information', 'None of the above', 'B', 'In Java, an exception caused by other exceptions is known as a chained exception. Generally, the first exception causes the second exception. It helps in identifying the cause of the exception. In chained exceptions, the debugging information is not '),
(36, 'java', 'In which memory a String is stored, when we create a string using new operator?', 'Stack', 'String memory', 'Heap memory', 'Random storage space', 'C', 'When a String is created using a new operator, it always created in the heap memory. Whereas when we create a string using double quotes, it will check for the same value as of the string in the string constant pool. If it is found, returns a referen'),
(37, 'java', 'What is the use of the intern() method?', 'It returns the existing string from memory', 'It creates a new string in the database', 'It modifies the existing string in the database', 'None of the above', 'A', 'The intern() method is used to return the existing strings from the database. In other words, the intern() method returns a reference of the string. For example, if the string constant pool already has a string object with the same value, the intern('),
(38, 'java', 'Which of the following is a marker interface?', 'Runnable interface', 'Remote interface', 'Readable interface', 'Result interface', 'B', 'A marker interface is an interface with no fields and methods. In other words, an empty interface (contains nothing) is known as the marker interface. Examples of marker interfaces are Cloneable, Serializable, ThreadSafe, and Remote interface.\r\n\r\nThe'),
(39, 'java', 'Which of the following is a reserved keyword in Java?', 'object', 'strictfp', 'main', 'system', 'B', 'In the above options, strictfp is the only reserved keyword of Java. The strictfp keyword is a modifier that restricts the floating-point calculations to assure portability and it was added in Java version 1.2. The objects are referring to those vari'),
(40, 'java', 'Which keyword is used for accessing the features of a package?', 'package', 'import', 'extends', 'export', 'B', 'The import keyword is used to access the classes and interfaces of a particular package to the current file. In other words, it is used to import the user-defined and built-in classes and interfaces into the source file of java so that the current fi'),
(41, 'java', 'In java, jar stands for_____.', 'JIn java, jar stands for_____.', 'Java Application Resource', 'Java Application Runner', 'None of the above', 'D', 'A Java ARchive (JAR) is a package file format used to combine all the metadata and resources into a single file. In other words, it is a file that contains several components, which make up a self-contained, executable, and deployable jar used to exe'),
(42, 'java', 'public class Test2 {  <br>\r\n    public static void main(String[] args) {  <br>\r\n        StringBuffer s1 = new <br>StringBuffer(\"Complete\");  <br>\r\n        s1.setCharAt(1,\"i\");  <br>\r\n        s1.setCharAt(7,\"d\");  <br>\r\n        System.out.println(s1);  <br>\r\n     }  <br>\r\n } <br>', 'Complete', 'Iomplede', 'Cimpletd', 'Coipletd', 'C', 'In the above code snippet, we have passed a string with value \"Complete\" and set character \"i\" and \"d\" at the index position 1 and 7, respectively. According to the string \"Complete,\" \"o\" is at position 1, and \"e\" is at the position 7. The setChar() '),
(43, 'java', 'Which of the following is false?', 'The rt.jar stands for the runtime jar', 'It is an optional jar file', 'It contains all the compiled class files', 'All the classes available in rt.jar is known to the JVM', 'B', 'The rt.jar stands for the runtime jar that comprises of all the compiled core class files for the Java Runtime Environment. It generally consists of classes like java.lang.String, java.lang.Object, java.io.Exception, etc., and all packages and classe'),
(44, 'java', 'What is the use of w in regex?', 'Used for a non-whitespace character', 'Used for a non-whitespace character', 'Used for a word character', 'Used for a non-word character', 'C', 'In java, the \"w\" regex is used to match with a word character consists of [a-zA-Z_0-9]. For example, w+ matches one or more word character that is same as ([a-zA-Z_0-9] +).'),
(45, 'java', 'Which of the given methods are of Object class?', 'notify(), wait( long msecs ), and synchronized()', 'wait( long msecs ), interrupt(), and notifyAll()', 'notify(), notifyAll(), and wait()', 'sleep( long msecs ), wait(), and notify()', 'C', 'The notify(), notifyAll(), and wait() are the methods of the Object class. The notify() method is used to raise a single thread that is waiting on the object\"s monitor. The notifyAll() method is similar to the notify() method, except that it wakes up'),
(46, 'java', 'Given that Student is a class, how many reference variables and objects are created by the following code?\r\nStudent studentName, studentId;  \r\nstudentName = new Student();  \r\nStudent stud_class = new Student();   ', 'Three reference variables and two objects are created.', 'Two reference variables and two objects are created.', 'One reference variable and two objects are created.', 'Three reference variables and three objects are created.', 'A', 'Explanation: In the above code, there are three reference variables and two objects. The studentName, studentId, and stud_class are the three reference variables. The objects are those variables that are created using the new operator, i.e., studentN'),
(47, 'java', '37) Which of the following is a valid syntax to synchronize the HashMap?\r\n\r\n', 'Map m = hashMap.synchronizeMap();', 'HashMap map =hashMap.synchronizeMap();', 'Map m1 = Collections.synchronizedMap(hashMap);', 'Map m2 = Collection.synchronizeMap(hashMap);', 'C', ' By default, the HashMap class is a non-synchronized collection class. The need for synchronization is to perform thread-safe operations on the class. To synchronize the HashMap class explicitly, we should use the Collections.synchronizedMap(hashMap)'),
(48, 'java', 'Given,\r\n\r\nArrayList list = new ArrayList();  <br>\r\nWhat is the initial quantity of the ArrayList list?\r\n\r\n', '5', '1', '0', '100', 'B', 'The initial or default quantity of an ArrayList is 10. It means when we create an ArrayList without specifying any quantity, it will be created with the default capacity, i.e., 10. Hence, an ArrayList with the default capacity can hold ten (10) value'),
(49, 'java', 'Which of the following is a mutable class in java?', 'java.lang.String', 'java.lang.Byte', 'java.lang.Short', 'java.lang.StringBuilder', 'D', 'A mutable class is a class in which changes can be made after its creation. We can modify the internal state and fields of a mutable class. The StringBuilder class is a mutable class, as it can be altered after it is created.\r\n\r\nThe String, Byte, and'),
(50, 'java', 'What will be the output of the following program?<br>\r\nabstract class MyFirstClass  <br>\r\n{  <br>\r\n     abstract num (int a, int b) {  }  <br>\r\n}  <br>', 'No error', 'Method is not defined properly', 'Constructor is not defined properly', 'Extra parentheses', 'B', 'Following are some rules for declaring an abstract method:\r\n\r\nAbstract methods do not specify a method body, but they only have a method signature.\r\nAbstract methods are always defined inside an abstract class.\r\nIn the above code, MyFirstClass is an '),
(51, 'java', 'What is meant by the classes and objects that dependents on each other?', 'Tight Coupling', 'Cohesion', 'Loose Coupling', 'None of the above', 'A', 'In tight coupling, a group of classes and objects are highly dependent on each other. Tight coupling is also used in some cases, like when an object creates some other objects that are going to be used by them.\r\n\r\nTight coupling is the correct answer'),
(52, 'java', 'Given,\r\n<br>\r\nint values[ ] = {1,2,3,4,5,6,7,8,9,10};  <br>\r\nfor(int i=0;i< Y; ++i)  <br>\r\nSystem.out.println(values[i]);  <br>\r\nFind the value of value[i]?', '10', '11', '15', 'None of the above', 'D', 'In the above code, we have not defined the variable Y. The code will not execute without any specific value for Y; it results in exception, as shown below.\r\n\r\nException in thread \"main\" java.lang.Error: Unresolved compilation problem:\r\n        Y cann'),
(53, 'java', 'Which of the following code segment would execute the stored procedure \"getPassword()\" located in a database server?\r\n\r\n', 'CallableStatement cs = connection.prepareCall(\"{call.getPassword()}\"); cs.executeQuery();', 'CallabledStatement callable = conn.prepareCall(\"{call getPassword()}\"); callable.executeUpdate();', 'CallableStatement cab = con.prepareCall(\"{call getPassword()}\"); cab.executeQuery();', 'Callablestatement cstate = connect.prepareCall(\"{call getpassword()}\"); cstate.executeQuery();', 'C', 'In Java, java.sql.CallableStatement interface is used to call the SQL stored procedures in the database. The stored procedures are similar to functions as they perform some specific tasks, except that they are only available in the database. The Call'),
(54, 'java', 'How many threads can be executed at a time?', 'Only one thread', 'Multiple threads', 'Only main (main() method) thread', 'Two threads', 'B', 'In Java, multiple threads can be executed at the same time. A Java standalone application always starts with a single thread known as the main thread that is associated with the main() method.\r\n\r\nIn the operating system, only one thread is executed a'),
(55, 'java', 'If three threads trying to share a single object at the same time, which condition will arise in this scenario?', 'Time-Lapse', 'Critical situation', 'Race condition', 'Recursion', 'C', 'If two or more threads are trying to access a common resource at the same time. This situation is known as race condition. It generally occurs during the execution of multi-threaded application. It also refers to a programming bug or issue that occur'),
(56, 'java', 'If a thread goes to sleep\r\n\r\n', 'It releases all the locks it has.', 'It does not release any locks.', 'It releases half of its locks.', 'It releases all of its lock except one.', 'B', 'The sleep() method does not release any locks of an object for a specific time or until an interrupt occurs. It leads to the poor performance or deadlock of threads. Whereas, the wait() method does not release the locks of an object.\r\n\r\nTherefore, wh'),
(57, 'java', 'Which of the following modifiers can be used for a variable so that it can be accessed by any thread or a part of a program?', 'global', 'transient', 'volatile', 'default', 'C', 'In Java, we can modify the values of a variable with the help of a reserved keyword known as volatile. It is a different way of making a class thread-safe. Thread-safe means that the methods and objects of a class are accessible by multiple threads a'),
(58, 'java', 'What is the result of the following program?<br>\r\npublic static synchronized void main(String[] args) throws  <br>\r\nInterruptedException {  <br>\r\n     Thread f = new Thread();  <br>\r\n      f.start();  <br>\r\n      System.out.print(\"A\");  <br>\r\n      f.wait(1000);  <br>\r\n      System.out.print(\"B\");  <br>\r\n}  ', 'It prints A and B with a 1000 seconds delay between them', 'It only prints A and exits', 'It only prints B and exits', 'A will be printed, and then an exception is thrown.', 'D', 'The InterruptedException is thrown when a thread is waiting, sleeping, or occupied. The output of the above code is shown below:\r\n\r\nA\r\nException in thread \"main\" java.lang.IllegalMonitorStateException\r\n	at java.lang.Object.wait(Native Method)\r\n	at co'),
(59, 'java', 'In character stream I/O, a single read/write operation performs _____.', 'Two bytes read/write at a time.', 'Eight bytes read/write at a time.', 'One byte read/write at a time.', 'Five bytes read/ write at a time.', 'A', 'There are two types of I/O stream. One is a byte stream, and the other is the character stream. The Byte stream is used to perform input or output 8-bit (equals to 1 byte) Unicode bytes whereas, the Character stream is used to read or write a 16-bit '),
(60, 'java', 'What is the default encoding for an OutputStreamWriter?', 'UTF-8', 'Default encoding of the host platform', 'UTF-12', 'None of the above', 'B', 'The OutputStreamWriter class translates Unicode character into bytes by using the character encoding. The character encoding can be either a default encoding dependent on the system or encoding that is explicitly defined. If no external encoding is s'),
(61, 'java', 'Which of the following option leads to the portability and security of Java?', 'Bytecode is executed by JVM', 'The applet makes the Java code secure and portable', 'Use of exception handling', 'Dynamic binding between objects', 'A', 'The output of the Java compiler is bytecode, which leads to the security and portability of the Java code. It is a highly developed set of instructions that are designed to be executed by the Java runtime system known as Java Virtual Machine (JVM). T'),
(62, 'java', 'Which of the following is not a Java features?', 'Dynamic', 'Architecture Neutral', 'Use of pointers', 'Object-oriented', 'C', 'he Java language does not support pointers; some of the major reasons are listed below:\r\n\r\nOne of the major factors of not using pointers in Java is security concerns. Due to pointers, most of the users consider C-language very confusing and complex.'),
(63, 'java', 'The u0021 article referred to as a\r\n\r\n', 'Unicode escape sequence', 'Octal escape', 'Hexadecimal', 'Line feed', 'A', 'In Java, Unicode characters can be used in string literals, comments, and commands, and are expressed by Unicode Escape Sequences. A Unicode escape sequence is made up of the following articles:\r\n\r\nA backslash \"\"(ASCII character 92)\r\nA \"u\" (ASCII 117'),
(64, 'java', '____ is used to find and fix bugs in the Java programs.', 'JVM', 'JRE', 'JDK', 'JDB', 'D', 'The Java Debugger (JDB or jdb) is a command-line java debugger that debugs the java class. It is a part of the Java Platform Debugger Architecture (JPDA) that helps in the inspections and debugging of a local or remote Java Virtual Machine (JVM).\r\n\r\n'),
(65, 'java', 'Which of the following is a valid declaration of a char?', 'char ch = \"utea\";', 'char ca = \"tea\";', 'char cr = u0223;', 'char cc = \"itea\";', 'A', 'A char literal may contain a Unicode character (UTF-16). We can directly use these characters only if our file system allows us, else use a Unicode escape (u) such as \"u02tee\". The char literals are always declared in single quotes (\").\r\n\r\nThe option'),
(66, 'java', 'What is the return type of the hashCode() method in the Object class?\r\n\r\n', 'Object', 'int', 'long', 'void', 'B', 'In Java, the return type of hashCode() method is an integer, as it returns a hash code value for the object.'),
(67, 'java', 'Which of the following is a valid long literal?', 'ABH8097', 'L990023', '904423', '0xnf029L', 'D', 'For every long literal to be recognized by Java, we need to add L character at the end of the expression. It can be either uppercase (L) or lowercase (l) character. However, it is recommended to use uppercase character instead of lowercase because th'),
(68, 'java', 'What does the expression float a = 35 / 0 return?', '0', 'Not a Number', 'Infinity', 'Run time exception', 'C', 'In Java, whenever we divide any number (double, float, and long except integer) by zero, it results in infinity. According to the IEEE Standard for Floating-Point Arithmetic (IEEE 754), if we divide 1/0 will give positive infinity, -1/0 will give neg'),
(69, 'java', 'Evaluate the following Java expression, if x=3, y=5, and z=10:\r\n\r\n++z + y - y + z + x++', '24', '23', '20', '25', 'D', ' In the above expression, ++z means that the value will first increment by 1, i.e. 12. Now, evaluate the statement by putting the values of x, y, and z. On evaluating the expression, we get 25, as shown below.\r\n<br>\r\n++z +y -y +z + x++ <br>\r\n11 + 5 -'),
(70, 'java', 'What will be the output of the following program?<br>\r\npublic class Test {  <br>\r\npublic static void main(String[] args) {  <br>\r\n    int count = 1;  <br>\r\n    while (count <= 15) {  <br>\r\n    System.out.println(count % 2 == 1 ? \"***\" : \"+++++\");  <br>\r\n    ++count;  <br>\r\n        }      // end while  <br>\r\n    }       // end main   <br>\r\n }  ', '15 times ***', '15 times +++++', '8 times *** and 7 times +++++', 'Both will print only once', 'C', 'In the above code, we have declared count = 1. The value of count will be increased till 14 because of the while (count<=15) statement. If the remainder is equal to 1 on dividing the count by 2, it will print (***) else print (+++++). Therefore, for '),
(71, 'java', 'Which of the following tool is used to generate API documentation in HTML format from doc comments in source code?', 'javap tool', 'javaw command', 'Javadoc tool', 'javah command', 'C', 'The Javadoc is a tool that is used to generate API documentation in HTML format from the Java source files. In other words, it is a program (tool) that reads a collection of source files into an internal form.'),
(72, 'java', 'Which of the following creates a List of 3 visible items and multiple selections abled?', 'new List(false, 3)', 'new List(3, true)', 'new List(true, 3)', 'new List(3, false)', 'B', 'From the above statements, the new List(3, true) is the correct answer; this is because of the constructor type. To create a list of 3 visible items along with the multiple selections abled, we have to use the following constructor of the List class.'),
(73, 'java', 'Which of the following for loop declaration is not valid?', 'for ( int i = 99; i >= 0; i / 9 )', 'for ( int i = 7; i <= 77; i += 7 )', 'for ( int i = 20; i >= 2; - -i )', 'for ( int i = 2; i <= 20; i = 2* i )', 'A', 'The first option is not a valid declaration as i/9 is not declared correctly. The correct statement will be:\r\n      for ( int i= 99; i>=0; i= i/9)\r\n\r\nThen the code would execute. But without assigning the value of i/9 to a variable, it would not exec'),
(74, 'java', 'Which method of the Class.class is used to determine the name of a class represented by the class object as a String?', 'getClass()', 'intern()', 'getName()', 'toString()', 'C', 'The getName() method of the Class class returns the name (as String) of the entity (class, interface) represented by this Class object. It is a non-static method, and available in the java.lang package.\r\n\r\nThe getClass() method of the Object class re'),
(75, 'java', 'In which process, a local variable has the same name as one of the instance variables?', 'Serialization', 'Variable Shadowing', 'Abstraction', 'Multi-threading', 'B', 'There are following reasons for considering a variable shadowing, they are listed below:\r\n\r\nWhen we define a variable in a local scope with a variable name same as the name of a variable defined in an instance scope.\r\nWhen a subclass declares a varia'),
(76, 'java', 'Which of the following is true about the anonymous inner class?', 'It has only methods', 'Objects can\"t be created', 'It has a fixed class name', 'It has no class name', 'D', 'Anonymous inner classes are the same as the local classes except that they don\"t have any name. The main use of it is to override methods of classes or interfaces. And the rest three options are false about the anonymous inner classes as it can have '),
(77, '', 'Which package contains the Random class?', 'java.util package', 'java.lang package', 'java.awt package', 'java.io package', 'A', 'The Random class is available in the java.util package. An object of the Random class is used to generate a series of pseudorandom numbers. And the object of this class is a thread-safe and cryptographically insecure object. The Random class provides'),
(78, 'java', 'What do you mean by nameless objects?', 'An object created by using the new keyword.', 'An object of a superclass created in the subclass.', 'An object without having any name but having a reference.', 'An object that has no reference.', 'D', 'The nameless objects are basically referred to as anonymous objects. The anonymous objects do not have any names. We can also say that, when an object is initialized but is not assigned to any reference variable, it is called an anonymous object. For'),
(79, 'java', 'An interface with no fields or methods is known as a ______.', 'Runnable Interface', 'Marker Interface', 'Abstract Interface', 'CharSequence Interface', 'B', 'An interface with no methods and fields is known as the marker interface. In other words, an empty interface (containing no fields and methods) is called a marker interface. In Java, the most commonly used marker interfaces are Serializable, Cloneabl'),
(80, 'java', 'Which of the following is an immediate subclass of the Panel class?', 'Applet class', 'Window class', 'Frame class', 'Dialog class', 'A', 'According to the class hierarchy of Java Swing, the Applet class is the direct subclass of the Panel class. You can go through the link, (https://www.javatpoint.com/java-swing) to deeply understand the class hierarchy diagram. The Panel class and Win'),
(81, 'java', 'Which of the following is a reserved keyword in Java?', 'object', 'strictfp', 'main', 'system', 'B', 'In the above options, strictfp is the only reserved keyword of Java. The strictfp keyword is a modifier that restricts the floating-point calculations to assure portability and it was added in Java version 1.2. The objects are referring to those vari'),
(82, 'java', 'Which keyword is used for accessing the features of a package?', 'package', 'import', 'extends', 'export', 'B', 'The import keyword is used to access the classes and interfaces of a particular package to the current file. In other words, it is used to import the user-defined and built-in classes and interfaces into the source file of java so that the current fi'),
(83, 'java', 'In java, jar stands for_____.', 'Java Archive Runner', 'Java Application Resource', 'Java Application Runner', 'None of the above', 'D', 'A Java ARchive (JAR) is a package file format used to combine all the metadata and resources into a single file. In other words, it is a file that contains several components, which make up a self-contained, executable, and deployable jar used to exe'),
(84, 'java', 'Which of the following is false?', 'The rt.jar stands for the runtime jar', 'It is an optional jar file', 'It contains all the compiled class files', 'All the classes available in rt.jar is known to the JVM', 'B', 'The rt.jar stands for the runtime jar that comprises of all the compiled core class files for the Java Runtime Environment. It generally consists of classes like java.lang.String, java.lang.Object, java.io.Exception, etc., and all packages and classe'),
(85, 'java', 'What is the use of w in regex?', 'Used for a whitespace character', 'Used for a non-whitespace character', 'Used for a word character', 'Used for a non-word character', 'C', 'In java, the \"w\" regex is used to match with a word character consists of [a-zA-Z_0-9]. For example, w+ matches one or more word character that is same as ([a-zA-Z_0-9] +).'),
(86, 'java', 'Which of the given methods are of Object class?', 'notify(), wait( long msecs ), and synchronized()', 'wait( long msecs ), interrupt(), and notifyAll()', 'notify(), notifyAll(), and wait()', 'sleep( long msecs ), wait(), and notify()', 'C', 'The notify(), notifyAll(), and wait() are the methods of the Object class. The notify() method is used to raise a single thread that is waiting on the object\"s monitor. The notifyAll() method is similar to the notify() method, except that it wakes up'),
(87, 'java', 'Given that Student is a class, how many reference variables and objects are created by the following code?<br>\r\nStudent studentName, studentId;  <br>\r\nstudentName = new Student();  <br>\r\nStudent stud_class = new Student();   ', 'Three reference variables and two objects are created.', 'Two reference variables and two objects are created.', 'One reference variable and two objects are created.', 'Three reference variables and three objects are created.', 'A', 'In the above code, there are three reference variables and two objects. The studentName, studentId, and stud_class are the three reference variables. The objects are those variables that are created using the new operator, i.e., studentName and stud_'),
(88, 'java', 'Which of the following is a valid syntax to synchronize the HashMap?', 'Map m = hashMap.synchronizeMap();', 'HashMap map =hashMap.synchronizeMap();', 'Map m1 = Collections.synchronizedMap(hashMap);', 'Map m2 = Collection.synchronizeMap(hashMap);', 'C', 'By default, the HashMap class is a non-synchronized collection class. The need for synchronization is to perform thread-safe operations on the class. To synchronize the HashMap class explicitly, we should use the Collections.synchronizedMap(hashMap) '),
(89, 'java', 'What is the initial quantity of the ArrayList list?\r\n\r\n', '5', '10', '0', '100', 'B', 'The initial or default quantity of an ArrayList is 10. It means when we create an ArrayList without specifying any quantity, it will be created with the default capacity, i.e., 10. Hence, an ArrayList with the default capacity can hold ten (10) value'),
(90, 'java', 'Which of the following is a mutable class in java?', 'java.lang.String', 'java.lang.Byte', 'java.lang.Short', 'java.lang.StringBuilder', 'D', 'A mutable class is a class in which changes can be made after its creation. We can modify the internal state and fields of a mutable class. The StringBuilder class is a mutable class, as it can be altered after it is created.\r\n\r\nThe String, Byte, and'),
(91, '', '', '', '', '', '', '', ''),
(92, '', '', '', '', '', '', '', ''),
(93, 'java', 'What is meant by the classes and objects that dependents on each other?', 'Tight Coupling', 'Cohesion', 'Loose Coupling', 'None of the above', 'A', 'In tight coupling, a group of classes and objects are highly dependent on each other. Tight coupling is also used in some cases, like when an object creates some other objects that are going to be used by them.\r\n\r\nTight coupling is the correct answer'),
(94, 'java', 'Which of the following code segment would execute the stored procedure \"getPassword()\" located in a database server?', 'CallableStatement cs = connection.prepareCall(\"{call.getPassword()}\"); cs.executeQuery();', 'CallabledStatement callable = conn.prepareCall(\"{call getPassword()}\"); callable.executeUpdate();', 'CallableStatement cab = con.prepareCall(\"{call getPassword()}\"); cab.executeQuery();', 'Callablestatement cstate = connect.prepareCall(\"{call getpassword()}\"); cstate.executeQuery();', 'C', 'In Java, java.sql.CallableStatement interface is used to call the SQL stored procedures in the database. The stored procedures are similar to functions as they perform some specific tasks, except that they are only available in the database. The Call'),
(95, 'java', 'How many threads can be executed at a time?', 'Only one thread', 'Multiple threads', 'Only main (main() method) thread', 'Two threads', 'B', 'In Java, multiple threads can be executed at the same time. A Java standalone application always starts with a single thread known as the main thread that is associated with the main() method.\r\n\r\nIn the operating system, only one thread is executed a'),
(96, 'java', ' If three threads trying to share a single object at the same time, which condition will arise in this scenario?', 'Time-Lapse', 'Critical situation', 'Race condition', 'Recursion', 'C', 'If two or more threads are trying to access a common resource at the same time. This situation is known as race condition. It generally occurs during the execution of multi-threaded application. It also refers to a programming bug or issue that occur'),
(97, 'java', 'Which of the following modifiers can be used for a variable so that it can be accessed by any thread or a part of a program?', 'global', 'transient', 'volatile', 'default', 'C', 'In Java, we can modify the values of a variable with the help of a reserved keyword known as volatile. It is a different way of making a class thread-safe. Thread-safe means that the methods and objects of a class are accessible by multiple threads a'),
(98, 'java', '\r\nNumber of primitive data types in Java are?', '6', '7', '8', '9', 'C', ''),
(99, 'java', 'What is the size of float and double in java?', '32 and 64', '32 and 32', '64 and 64', '64 and 32', 'A', ''),
(100, 'java', 'JDK stands for ____.', 'Java development kit', 'Java deployment kit', 'JavaScript deployment kit', 'None of these', 'A', 'JDK stands for Java Development Kit. It is a platform to develop and run Java applications.\r\n\r\n'),
(101, 'java', 'JRE stands for ___.', 'Java run ecosystem', 'JDK runtime Environment', 'Java Runtime Environment', 'None of these', 'C', 'JRE stands for Java Runtime Environment which provides an environment to run a java program.\r\n\r\n'),
(102, 'java', 'What makes the Java platform independent?', 'Advanced programming language', 'It uses bytecode for execution', 'Class compilation', 'All of these', 'B', 'In Java, programs are compiled into byte code and that byte code is platform-independent.\r\n\r\n'),
(103, 'java', 'Can we keep a different name for the java class name and java file name?', 'Yes', 'No', 'don\"t know', 'none of the above', 'A', 'we can keep a different name'),
(104, 'java', 'What are the types of memory allocated in memory in java?', 'Heap memory', 'Stack memory', 'Both A and B', 'None of these', 'C', 'Memory allocation in java occurs in two ways, mainly, stack and heap space.\r\n\r\n'),
(105, 'java', 'Multiline comment is created using ___.', '//', '/* */', 'None of these\r\n', 'All of these', 'B', 'Multi-line comments start with /* and ends with */. Any text between /* and */ will be ignored by Java.'),
(106, 'java', 'What is the entry point of a program in Java?', 'main() method', 'The first line of code', 'Last line of code', 'main class', 'A', 'Generally, the main() method is treated as the point where the flow of code starts.\r\n\r\n'),
(107, 'java', 'Which keyword in java is used for exception handling?', 'exep', 'excepHand', 'throw', 'All of these', 'C', 'the throw is a keyword introduced in java for exception handling.\r\n\r\n'),
(108, 'java', 'Which class in Java is used to take input from the user?', 'Scanner', 'Input', 'Applier', 'None of these', 'A', 'The Scanner class is used to get user input, and it is found in the java. util package.\r\n\r\n'),
(109, 'java', 'Method used to take a string as input in Java?', 'next()', 'nextLine()', 'Both A. and B.', 'None of these', 'B', 'The next() method can read the input only till the space. It can\"t read two words separated by space, while the nextLine() reads input including space between the words (that is, it reads till the end of line \n).'),
(110, 'java', 'Which of the following is the correct syntax to create a variable in Java?', 'var name;', 'int name;', 'var name int;', 'All of these', 'B', 'Read here: Java variable declarations'),
(111, 'java', 'Which of the following is the correct syntax to create a variable in Java?', 'var name;', 'int name;', 'var name int;', 'All of these', 'B', 'Read here: Java variable declarations'),
(112, 'python', ' Who developed Python Programming Language?', 'Wick van Rossum', 'Rasmus Lerdorf', ' Guido van Rossum', 'Niene Stom', 'C', ' Python language is designed by a Dutch programmer Guido van Rossum in the Netherlands. '),
(113, 'python', '', 'object-oriented programming', 'structured programming', ' functional programming', 'all of the mentioned', 'D', ': Python is an interpreted programming language, which supports object-oriented, structured, and functional programming.'),
(114, 'python', '. Is Python case sensitive when dealing with identifiers?', 'no', 'yes', 'machine dependent', 'none of the mentioned', 'B', ' Case is always significant while dealing with identifiers in python.'),
(115, 'python', 'Which of the following is the correct extension of the Python file?', ' .python', ' .pl', ' .py', '.p', 'C', ' \".py\" is the correct extension of the Python file. Python programs can be written in any text editor. To save these programs we need to save in files with file extension \".py\".'),
(116, 'python', ' Is Python code compiled or interpreted?', 'Python code is both compiled and interpreted', 'Python code is neither compiled nor interpreted', 'Python code is only compiled', ' Python code is only interpreted', 'A', 'Many languages have been implemented using both compilers and interpreters, including C, Pascal, and Python.'),
(117, 'python', 'All keywords in Python are in _________', 'Capitalized', 'lower case', 'UPPER CASE', 'None of the mentioned', 'D', ' True, False and None are capitalized while the others are in lower case.'),
(118, 'python', 'What will be the value of the following Python expression? <br>\r\n4 + 3 % 5', '7', '2', '4', '1', 'A', 'The order of precedence is: %, +. Hence the expression above, on simplification results in 4 + 3 = 7. Hence the result is 7.'),
(119, 'python', 'Which of the following is used to define a block of code in Python language?', 'Indentation', ' Key', 'Brackets', 'All of the mentioned', 'A', ' In Python, to define a block of code we use indentation. Indentation refers to whitespaces at the beginning of the line.'),
(120, 'python', ' Which keyword is used for function in Python language?', 'Function', 'def', 'Fun', 'Define', 'B', 'The def keyword is used to create, (or define) a function in python.'),
(121, 'python', ' Which of the following character is used to give single-line comments in Python?', '//', '#', '!', '/*', 'B', 'To write single-line comments in Python use the Hash character (#) at the beginning of the line. It is also called number sign or pound sign. To write multi-line comments, close the text between triple quotes.\r\nExample: “”” comment\r\ntext “””'),
(122, 'python', '\r\nWhat will be the output of the following Python code?<br>\r\ni = 1<br>\r\nwhile True: <br>\r\n    if i%3 == 0: <br>\r\n        break <br>\r\n    print(i) <br>\r\n \r\n    i + = 1', '1 2 3', 'error', '1 2', 'none of the mentioned', 'B', 'SyntaxError, there shouldn’t be a space between + and = in +=.'),
(123, 'python', 'SyntaxError, there shouldn’t be a space between + and = in +=.', ' sys.version(1)', 'sys.version(0)', ' sys.version()', 'sys.version', 'D', ' The function sys.version can help us to find the version of python that we are currently working on. It also contains information on the build number and compiler used. For example, 3.5.2, 2.7.3 etc. this function also returns the current date, time'),
(124, 'python', '. Python supports the creation of anonymous functions at runtime, using a construct called __________', 'pi', 'anonymous', 'lambda', 'none of the mentioned', 'C', ' Python supports the creation of anonymous functions (i.e. functions that are not bound to a name) at runtime, using a construct called lambda. Lambda functions are restricted to a single expression. They can be used wherever normal functions can be '),
(125, 'python', ' What is the order of precedence in python?', 'Exponential, Parentheses, Multiplication, Division, Addition, Subtraction', ' Exponential, Parentheses, Division, Multiplication, Addition, Subtraction', ' Parentheses, Exponential, Multiplication, Division, Subtraction, Addition', ' Parentheses, Exponential, Multiplication, Division, Addition, Subtraction', 'D', 'For order of precedence, just remember this PEMDAS (similar to BODMAS).'),
(126, 'python', ' What will be the output of the following Python code snippet if x=1?', '4', '2', '8', '1', 'A', 'The binary form of 1 is 0001. The expression x<<2 implies we are performing bitwise left shift on x. This shift yields the value: 0100, which is the binary form of the number 4.'),
(127, 'python', '. What does pip stand for python?', 'Pip Installs Python', 'Pip Installs Packages', 'Preferred Installer Program', 'All of the mentioned', 'C', ' pip is a package manager for python. Which is also called Preferred Installer Program.');
INSERT INTO `practice_questions` (`id`, `course_name`, `question`, `optionA`, `optionB`, `optionC`, `optionD`, `answer`, `explaination`) VALUES
(128, 'python', ' Which of the following is true for variable names in Python?', 'underscore and ampersand are the only two special characters allowed', 'unlimited length', 'all private members must have leading and trailing underscores', ' none of the mentioned', 'B', ' Variable names can be of any length.'),
(129, 'python', ' What are the values of the following Python expressions?<br>\r\n 2**(3**2)<br>\r\n (2**3)**2<br>\r\n 2**3**2', ' 512, 64, 512', ' 512, 512, 512', ' 64, 512, 64', '64, 64, 64', 'A', ' Expression 1 is evaluated as: 2**9, which is equal to 512. Expression 2 is evaluated as 8**2, which is equal to 64. The last expression is evaluated as 2**(3**2). This is because the associativity of ** operator is from right to left. Hence the resu'),
(130, 'python', 'Which of the following is the truncation division operator in Python?', '/', '//', '|', '%', 'B', ' // is the operator for truncation division. It is called so because it returns only the integer part of the quotient, truncating the decimal part. For example: 20//3 = 6.'),
(131, 'python', 'What will be the output of the following Python code?<br>\r\nl=[1, 0, 2, 0, \"hello\", \', []] <br>\r\nlist(filter(bool, l))', '[1, 0, 2, \"hello\", ”, []] ', 'Error', '[1, 2, ‘hello’] ', '[1, 0, 2, 0, ‘hello’, ”, []] ', 'C', 'The code shown above returns a new list containing only those elements of the list l which do not amount to zero. Hence the output is: [1, 2, \"hello\"].'),
(132, 'python', 'Which of the following functions is a built-in function in python?', ' factorial()', ' print()', 'seed()', ' sqrt()', 'B', ' The function seed is a function which is present in the random module. The functions sqrt and factorial are a part of the math module. The print function is a built-in function which prints a value directly to the system output.'),
(133, 'python', ' Which of the following is the use of id() function in python?', 'Every object doesn’t have a unique id', ' Id returns the identity of the object', 'All of the mentioned', ' None of the mentioned', 'B', ' Each object in Python has a unique id. The id() function returns the object’s id. '),
(134, 'python', ' The following python program can work with ____ parameters.<br>\r\ndef f(x): <br>\r\n    def f1(*args, **kwargs):\r\n           print(\"Sanfoundry\")\r\n           return x(*args, **kwargs)\r\n    return f1', ' any number of', '0', '1', '2', 'A', ' The code shown above shows a general decorator which can work with any number of arguments.'),
(135, 'python', 'What will be the output of the following Python function? <br>\r\nmin(max(False,-3,-4), 2,7)', '-4', '-3', '2', 'False', 'D', 'The function max() is being used to find the maximum value from among -3, -4 and false. Since false amounts to the value zero, hence we are left with min(0, 2, 7) Hence the output is 0 (false).'),
(136, 'python', 'Which of the following is not a core data type in Python programming?', 'Tuples', 'Lists', 'Class', 'Dictionary', 'C', 'Class is a user-defined data type. '),
(137, 'python', ' What will be the output of the following Python expression if x=56.236?<br>\r\nprint(\"%.2f\"%x)', '56.236', '56.23', ' 56.0000', '56.24', 'C', ' The expression shown above rounds off the given number to the number of decimal places specified. Since the expression given specifies rounding off to two decimal places, the output of this expression will be 56.24. Had the value been x=56.234 (last'),
(138, 'python', ' Which of these is the definition for packages in Python?', 'A set of main modules', 'A folder of python modules', 'A number of files containing Python definitions and statements', 'A set of programs making use of Python modules', 'B', ' A folder of python programs is called as a package of modules.'),
(139, 'python', 'What will be the output of the following Python function? <br>\r\nlen([\"hello\",2, 4, 6])', 'Error', '6', '4', '3', 'C', ' The function len() returns the length of the number of elements in the iterable. Therefore the output of the function shown above is 4.'),
(140, 'python', 'What will be the output of the following Python code?<br>\r\nx = \"abcd\" <br>\r\nfor i in x: <br>\r\n    print(i.upper())', 'a B C D', 'b) a b c d', 'Cerror', 'D', '', ''),
(141, 'python', 'What is the order of namespaces in which Python looks for an identifier?', 'Python first searches the built-in namespace, then the global namespace and finally the local namespace', 'Python first searches the built-in namespace, then the local namespace and finally the global namespace', 'Python first searches the local namespace, then the global namespace and finally the built-in namespace', 'Python first searches the global namespace, then the local namespace and finally the built-in namespace', 'C', 'Python first searches for the local, then the global and finally the built-in namespace.'),
(142, '', 'What will be the output of the following Python code snippet?<br>\r\nfor i in [1, 2, 3, 4][::-1]: <br>\r\n    print(i, end=)', '4 3 2 1', 'Error', '1 2 3 4', 'none of the mentioned', 'A', '[::-1] reverses the list.'),
(143, 'python', 'hat will be the output of the following Python statement? <br>\r\n>>>\"a\"+\"bc\"', 'bc', 'abc', 'a', 'bca', 'B', 'perator is concatenation operator. '),
(144, 'python', ' function is called when the following Python program is executed? <br>\r\nf = foo() <br>\r\nformat(f)', 'str()', ' format()', '__str__()', ' __format__()', 'C', ' Both str(f) and format(f) call f.__str__().'),
(145, 'python', ' Which one of the following is not a keyword in Python language?', 'pass', 'eval', 'assert', 'nonlocal', 'B', 'eval can be used as a variable.'),
(146, 'python', ' What will be the output of the following Python code?<br>\r\nclass tester: <br>\r\n    def __init__(self, id): <br>\r\n        self.id = str(id) <br>\r\n        id=\"224\" <br>\r\n \r\n>>>temp = tester(12) <br>\r\n>>>print(temp.id)', '12', '224', 'none', 'error', 'A', ' Id in this case will be the attribute of the instance. '),
(147, 'python', ' What will be the output of the following Python program? <br>\r\ndef foo(x): <br>\r\n    x[0] = [\"def\"] <br>\r\n    x[1] = [\"abc\"] <br>\r\n    return id(x) <br>\r\nq = [\"abc\", \"def\"]\r\nprint(id(q) == foo(q))', 'Error', 'None', 'False', 'True', 'D', 'The same object is modified in the function.'),
(148, 'python', ' What will be the output of the following Python program? <br>\r\ndef foo(x): <br>\r\n    x[0] = [\"def\"] <br>\r\n    x[1] = [\"abc\"] <br>\r\n    return id(x) <br>\r\nq = [\"abc\", \"def\"]\r\nprint(id(q) == foo(q))', 'Error', 'None', 'False', 'True', 'D', 'The same object is modified in the function.'),
(149, 'python', ' What will be the output of the following Python program? <br>\r\ndef foo(x): <br>\r\n    x[0] = [\"def\"] <br>\r\n    x[1] = [\"abc\"] <br>\r\n    return id(x) <br>\r\nq = [\"abc\", \"def\"]\r\nprint(id(q) == foo(q))', 'Error', 'None', 'False', 'True', 'D', 'The same object is modified in the function.'),
(150, 'python', ' What will be the output of the following Python program? <br>\r\ndef foo(x): <br>\r\n    x[0] = [\"def\"] <br>\r\n    x[1] = [\"abc\"] <br>\r\n    return id(x) <br>\r\nq = [\"abc\", \"def\"]\r\nprint(id(q) == foo(q))', 'Error', 'None', 'False', 'True', 'D', 'The same object is modified in the function.'),
(151, 'python', ' What will be the output of the following Python program? <br>\r\ndef foo(x): <br>\r\n    x[0] = [\"def\"] <br>\r\n    x[1] = [\"abc\"] <br>\r\n    return id(x) <br>\r\nq = [\"abc\", \"def\"]\r\nprint(id(q) == foo(q))', 'Error', 'None', 'False', 'True', 'D', 'The same object is modified in the function.'),
(152, 'python', 'Which module in the python standard library parses options received from the command line?', ' getarg', 'getopt', 'main', 'os', 'B', 'getopt parses options received from the command line.'),
(153, 'python', ' What arithmetic operators cannot be used with strings in Python?', '*', '-', '+', 'All of the mentioned', 'B', ' + is used to concatenate and * is used to multiply strings.'),
(154, 'python', 'What will be the output of the following Python code? <br>\r\nprint(\"abc. DEF\".capitalize())', 'Abc. def', ' abc. def', 'Abc. Def', 'ABC. DEF', 'A', 'The first letter of the string is converted to uppercase and the others are converted to lowercase.'),
(155, 'python', ' Which of the following statements is used to create an empty set in Python?', '( )', '[ ] ', '{ }', 'set()', 'D', ' { } creates a dictionary not a set. Only set() creates an empty set. '),
(156, 'cpp', ' What will be the value of ‘result’ in following Python program? <br>\r\nlist1 = [1,2,3,4] <br>\r\nlist2 = [2,4,5,6] <br>\r\nlist3 = [2,6,7,8] <br>\r\nresult = list() <br>\r\nresult.extend(i for i in list1 if i not in (list2+list3) and i not in result) <br>\r\nresult.extend(i for i in list2 if i not in (list1+list3) and i not in result) <br>\r\nresult.extend(i for i in list3 if i not in (list1+list2) and i not in result)', '[1, 3, 5, 7, 8] ', '[1, 7, 8] ', '[1, 2, 4, 7, 8] ', 'error', 'A', ' Here, ‘result’ is a list which is extending three times. When first time ‘extend’ function is called for ‘result’, the inner code generates a generator object, which is further used in ‘extend’ function. This generator object contains the values whi'),
(157, 'python', ' To add a new element to a list we use which Python command?', 'list1.addEnd(5)', 'list1.addLast(5)', 'list1.append(5)', 'list1.add(5)', 'C', ' We use the function append to add an element to the list. '),
(158, '', '0', ' * abcde *', ') *abcde *', ' * abcde*', '* abcde *', 'B', ' Padding is done towards the right-hand-side first when the final string is of even length.'),
(159, 'python', 'What will be the output of the following Python code? <br>\r\n>>>list1 = [1, 3] <br>\r\n>>>list2 = list1 <br>\r\n>>>list1[0] = 4 <br>\r\n>>>print(list2)', ' [1, 4] ', ' [1, 3, 4] ', ' [4, 3] ', '[1, 3] ', 'C', ' Lists should be copied by executing [:] operation.'),
(160, 'python', ' Which one of the following is the use of function in python?', 'Functions don’t provide better modularity for your application', 'you can’t also create your own functions', ' Functions are reusable pieces of programs', ' All of the mentioned', 'C', ': Functions are reusable pieces of programs. They allow you to give a name to a block of statements, allowing you to run that block using the specified name anywhere in your program and any number of times. '),
(161, '', ' Which of the following Python statements will result in the output: 6? <br>\r\nA = [[1, 2, 3], <br>\r\n     [4, 5, 6], <br>\r\n     [7, 8, 9]]', 'A[2][1] ', 'A[1][2] ', 'A[3][2] ', 'A[2][3] ', 'B', ' The output that is required is 6, that is, row 2, item 3. This position is represented by the statement: A[1][2].'),
(162, 'python', 'What is the maximum possible length of an identifier in Python?', '79 characters', '31 characters', '63 characters', ' none of the mentioned', 'D', ' Identifiers can be of any length.'),
(163, 'python', 'What will be the output of the following Python program? <br>\r\ni = 0 <br>\r\nwhile i < 5: <br>\r\n    print(i) <br>\r\n    i += 1 <br>\r\n    if i == 3: <br>\r\n        break <br>\r\nelse: <br>\r\n    print(0)', 'error', ' 0 1 2 0', '0 1 2', 'none of the mentioned', 'C', 'The else part is not executed if control breaks out of the loop.'),
(164, 'python', 'hat will be the output of the following Python code?\r\nx = \"abcd\" <br>\r\nfor i in range(len(x)): <br>\r\n    print(i)', 'error', '1 2 3 4', ' a b c d', '0 1 2 3', 'D', ' i takes values 0, 1, 2 and 3.'),
(165, 'python', ' What are the two main types of functions in Python?', 'System function', 'Custom function', ' Built-in function & User defined function', 'User function', 'C', 'Built-in functions and user defined ones. The built-in functions are part of the Python language. Examples are: dir(), len() or abs(). The user defined functions are functions created with the def keyword. '),
(166, 'python', ' What will be the output of the following Python program?<br>\r\ndef addItem(listParam): <br>\r\n    listParam += [1] <br>\r\n \r\nmylist = [1, 2, 3, 4] <br>\r\naddItem(mylist) <br>\r\nprint(len(mylist))', '5', '8', '2', '1', 'A', ' + will append the element to the list.'),
(167, 'python', 'Which of the following is a Python tuple?', ' {1, 2, 3}', ' {}', '[1, 2, 3] ', ' (1, 2, 3)', 'D', 'Tuples are represented with round brackets.'),
(168, 'python', 'What will be the output of the following Python code snippet? <br>\r\nz=set(\"abc$de\") <br>\r\n\"a\" in z', 'Error', 'True', 'False', 'No output', 'B', ': The code shown above is used to check whether a particular item is a part of a given set or not. Since ‘a’ is a part of the set z, the output is true. Note that this code would result in an error in the absence of the quotes.'),
(169, 'python', 'What will be the output of the following Python expression? <br>\r\nround(4.576)', '4', '4.6', '5', '4.5', 'C', ' This is a built-in function which rounds a number to give precision in decimal digits. In the above case, since the number of decimal places has not been specified, the decimal number is rounded off to a whole number. Hence the output will be 5.'),
(170, 'python', ' Which of the following is a feature of Python DocString?', 'In Python all functions should have a docstring', 'Docstrings can be accessed by the __doc__ attribute on objects', 'It provides a convenient way of associating documentation with Python modules, functions, classes, and methods', 'All of the mentioned', 'D', 'Python has a nifty feature called documentation strings, usually referred to by its shorter name docstrings. DocStrings are an important tool that you should make use of since it helps to document the program better and makes it easier to understand.'),
(171, 'python', 'What will be the output of the following Python code? <br>\r\nprint(\"Hello {0[0]} and {0[1]}\".format((\"foo\", \"bin\"\r\n)))', 'Hello (\"foo\", \"bin\") and (\"foo\", \"bin\")', 'Error', 'Hello foo and bin', 'None of the mentioned', 'C', ' The elements of the tuple are accessed by their indices.'),
(172, 'python', 'What is output of print(math.pow(3, 2))?', '9.0', 'None', '9', 'none of the mentioned', 'A', ' math.pow() returns a floating point number.'),
(173, 'python', ' Which of the following is the use of id() function in python?', ' Every object in Python doesn’t have a unique id', 'In Python Id function returns the identity of the object', 'None of the mentioned', 'All of the mentioned', 'B', ' Each object in Python has a unique id. The id() function returns the object\"s id. '),
(174, 'python', ' What will be the output of the following Python code? <br>\r\nx = [[0], [1]] <br>\r\nprint((.join(list(map(str, x))),))', '01', '[0] [1] ', '(\"01\")', ' (\"[0] [1]\",)', 'D', ' (element,) is not the same as element. It is a tuple with one item.'),
(175, '', ' The process of pickling in Python includes ____________', 'conversion of a Python object hierarchy into byte stream', 'conversion of a datatable into a list', 'conversion of a byte stream into Python object hierarchy', 'conversion of a list into a datatable', 'A', ' Pickling is the process of serializing a Python object, that is, conversion of a Python object hierarchy into a byte stream. The reverse of this process is known as unpickling.'),
(176, 'python', 'What will be the output of the following Python code? <br>\r\ndef foo(): <br>\r\n    try: <br>\r\n        return 1 <br>\r\n    finally: <br>\r\n        return 2 <br>\r\nk = foo() <br>\r\nprint(k)', 'error, there is more than one return statement in a single try-finally block', '3', '2', '1', 'C', ' The finally block is executed even there is a return statement in the try block.'),
(177, 'python', 'What is the maximum possible length of an identifier?', '16', '32', '64', 'none of the mentioned', 'D', 'The maximum possible length of an identifier is not defined in the python language. It can be of any number.'),
(178, 'python', 'Who developed the Python language?', 'Zim Den', 'Guido van Rossum', 'Niene Stom', 'Wick van Rossum', 'B', ' Python language was developed by Guido van Rossum in the Netherlands.'),
(179, 'python', ' Python language was developed by Guido van Rossum in the Netherlands.', '1995', '1972', '1981', '1989', 'D', ': Python language was developed by Guido van Rossum in 1989.'),
(180, 'python', 'In which language is Python written?', 'English', 'PHP', 'C', 'All of the above', 'C', ' Python is written in C programming language, and it is also called CPython.'),
(181, 'python', 'Which one of the following is the correct extension of the Python file?', '.py', '.python', '.p', 'None of these', 'A', '\".py\" is the correct extension of the Python file. '),
(182, 'python', 'In which year was the Python 3.0 version developed?', '2008', '2000', '2010', '2005', 'A', 'Python 3.0 version was developed on December 3, 2008.'),
(183, 'python', 'What do we use to define a block of code in Python language?', 'Key', 'Brackets', 'Indentation', 'None of these', 'C', ' Python uses indentation to define blocks of code. Indentations are simply spaces or tabs used as an indicator that is part of the indent code child. As used in curly braces C, C++, and Java.'),
(184, 'python', ' Which of the following statements is correct regarding the object-oriented programming concept in Python?', 'Classes are real-world entities while objects are not real', 'Objects are real-world entities while classes are not real', 'Both objects and classes are real-world entities', 'All of the above', 'B', ' Objects are real-world entities while classes are not real'),
(185, 'python', 'What is the method inside the class in python language?', 'Object', 'Function', 'Attribute', 'Argument', 'B', ' Function is also known as the method.'),
(186, 'python', ' Which of the following declarations is incorrect?', '_x = 2', '__x = 3', '__xyz__ = 5', 'None of these', 'D', ' All declarations will execute successfully but at the expense of low readability.'),
(187, 'python', 'Why does the name of local variables start with an underscore discouraged', 'To identify the variable', 'It confuses the interpreter', 'It indicates a private variable of a class', 'None of these', 'C', ': Since there is no concept of private variables in Python language, the major underscore is used to denote variables that cannot be accessed from outside the class.'),
(188, 'python', 'Which of the following is not a keyword in Python language?', 'val', 'raise', 'try', 'with', 'A', ' \"val\" is not a keyword in python language.'),
(189, 'python', '', 'All variable names must begin with an underscore.', 'Unlimited length', 'The variable name length is a maximum of 2.', 'All of the above', 'B', 'None'),
(190, 'cpp', ' Which of the following declarations is incorrect in python language?', 'xyzp = 5,000,000', 'x y z p = 5000 6000 7000 8000', 'x,y,z,p = 5000, 6000, 7000, 8000', 'x_y_z_p = 5,000,000', 'B', ' Spaces are not allowed in variable names.'),
(191, 'python', ' Which of the following words cannot be a variable in python language?', '_val', 'val', 'try', '_try_', 'C', '\"try\" is a keyword.'),
(192, 'python', 'Which of the following operators is the correct option for power(ab)?', 'a ^ b', 'a**b', 'a ^ ^ b', 'a ^ * b', 'B', ' The power operator in python is a**b, i.e., 2**3=8.'),
(193, 'python', ') Which of the following precedence order is correct in Python?', 'Parentheses, Exponential, Multiplication, Division, Addition, ', 'Multiplication, Division, Addition, Subtraction, Parentheses, Exponential', 'Division, Multiplication, Addition, Subtraction, Parentheses, Exponential', 'Exponential, Parentheses, Multiplication, Division, Addition, Subtraction', 'A', 'PEMDAS (similar to BODMAS).'),
(194, 'python', 'Which one of the following has the same precedence level?', 'Division, Power, Multiplication, Addition and Subtraction', 'Division and Multiplication', 'Subtraction and Division', 'Power and Division', 'B', 'None'),
(195, 'python', 'Which one of the following has the highest precedence in the expression?', 'Division', 'Subtraction', 'Power', 'Parentheses', 'D', 'PEMDAS (similar to BODMAS).'),
(196, 'python', 'Which of the following functions is a built-in function in python language?', 'val()', 'print()', 'print()', 'None of these', 'B', ' The print() function is a built-in function in python language that prints a value directly to the system.'),
(197, 'python', ' Study the following function:<br>\r\nround(4.576)  <br>\r\nWhat will be the output of this function?', '4', '6', '576', '5', 'D', 'The round function is a built-in function in the Python language that round-off the value (like 3.85 is 4), so the output of this function will be 5.'),
(198, 'python', 'Which of the following is correctly evaluated for this function?<br>\r\npow(x,y,z)  \r\n', '(x**y) / z', '(x / y) * z', '(x**y) % z', '(x / y) / z', 'C', 'None'),
(199, 'python', ' Study the following function:<br>\r\nall([2,4,0,6])  \r\nWhat will be the output of this function?\r\n', 'False', 'True', '0', 'Invalid code', 'A', 'If any element is zero, it returns a false value, and if all elements are non-zero, it returns a true value. Hence, the output of this \"all([2,4,0,6])\" function will be false.'),
(200, 'python', 'Study the following program:<br>\r\nx = 1  <br>\r\nwhile True:  <br>\r\n    if x % 5 = = 0:  <br>\r\n        break  <br>\r\n    print(x)   <br>\r\n    x + = 1  <br>\r\nWhat will be the output of this code?\r\n', 'Error', '2 1', '0 3 1', 'none of the mentioned', 'A', 'Syntax error, there should not be a space between + and =.'),
(201, 'python', ' Which one of the following syntaxes is the correct syntax to read from a simple text file stored in \'d:java.txt\'?', 'Infile = open(\'d:\\java.txt\', \'r\')', 'Infile = open(file=\'d:\\java.txt\', \'r\')', 'Infile = open(\'d:java.txt\',\'r\')', 'Infile = open.file(\'d:\\java.txt\',\'r\')', 'A', 'None'),
(202, 'python', 'Study the following code: <br>\r\nx = [\"XX\", \"YY\"]  <br>\r\nfor i in a:  <br>\r\n    i.lower()  <br>\r\nprint(a)  <br>\r\nWhat will be the output of this program?\r\n', '[\"XX\", \"YY\"]', '[\"xx\", \"yy\"]', '[XX, yy]', 'None of these', 'A', 'None'),
(203, 'python', 'Study the following function: <br>\r\nimport math  <br>\r\nabs(math.sqrt(36))  <br>\r\nWhat will be the output of this code?\r\n', 'Error', '-6', '6', '6.0', 'D', ' This function prints the square of the value. '),
(204, 'python', 'Study the following function:<br>\r\nany([5>8, 6>3, 3>1])  <br>', 'False', 'True', 'invalid code', 'none of the mentioned', 'B', 'none'),
(205, 'python', ' Study the following statement:\r\n<br>\r\n>>>\"a\"+\"bc\"  <br>\r\nWhat will be the output of this statement?', 'a+bc', 'abc', 'a bc', 'a', 'B', 'In Python, the \"+\" operator acts as a concatenation operator between two strings. '),
(206, 'python', 'Study the following code:<br>\r\n>>>\"javatprint\"[5:]  <br>\r\nWhat will be the output of this code?', 'avap', 'java', 'print', 'none of the mentioned', 'C', 'Slice operation is performed on the string.'),
(207, 'python', 'The output to execute string.ascii_letters can also be obtained from:?', 'character', 'ascii_lowercase_string.digits', 'lowercase_string.upercase', 'ascii_lowercase+string.ascii_upercase', 'D', 'None'),
(208, 'python', 'Study the following statements: <br>\r\n>>> str1 = \"javat\"  <br>\r\n>>> str2 = \":\"  <br>\r\n>>> str3 = \"point\"  <br>\r\n>>> str1[-1:]  <br>\r\nWhat will be the output of this statement?', 't', 'j', 'point', 'java', 'A', 'The correct output of this program is \"t\" because -1 corresponds to the last index.'),
(209, 'python', 'Study the following statements: <br>\r\n>>> print(0xA + 0xB + 0xC)  <br>\r\nWhat will be the output of this statement?', '33', '63', '0xA + 0xB + 0xC', 'none of the mentioned', 'A', ' A, B and C are hexadecimal integers with values 10, 11 and 12 respectively, so the sum of A, B and C is 33.'),
(210, 'python', 'Study the following statements:\r\n\r\n>>> print(ord(\"h\") - ord(\"z\"))  \r\nWhat will be the output of this statement?', '18', '-18', '17', '-17', 'B', 'ASCII value of h is less than the z. Hence the output of this code is 104-122, which is equal to -18.'),
(211, 'python', 'Study the following program:<br>\r\na = 1  <br>\r\nwhile True: <br> \r\n    if a % 7 = = 0:  <br>\r\n        break  <br>\r\n    print(a)  <br>\r\n    a += 1  <br>\r\nWhich of the following is correct output of this program?', '1 2 3 4 5', '1 2 3 4 5 6', '1 2 3 4 5 6 7', 'Invalid syntax', 'B', 'None'),
(212, 'python', 'Study the following program:<br>\r\ni = 0<br>  \r\nwhile i < 5:<br>  \r\n    print(i)  <br>\r\n    i += 1  <br>\r\n    if i == 3:  <br>\r\n        break  <br>\r\nelse:  <br>\r\n    print(0)  <br>\r\nWhat will be the output of this statement?', '1 2 3', '0 1 2 3', '0 1 2', '3 2 1', 'C', 'None'),
(213, 'python', 'Study the following program:<br>\r\ni = 0  <br>\r\nwhile i < 3:<br>  \r\n    print(i)  <br>\r\n    i += 1  <br>\r\nelse:  <br>\r\n    print(0) <br> \r\nWhat will be the output of this statement?', '0 1', '0 1 2', '0 1 2 0', '0 1 2 3', 'C', 'None'),
(214, 'python', 'Study the following program: <br>\r\nz = \"xyz\"  <br>\r\nj = \"j\"  <br>\r\nwhile j in z:  <br>\r\n    print(j, end=\" \")  <br>\r\nWhat will be the output of this statement?', 'xyz', 'No output', 'x y z', 'j j j j j j j..', 'B', '\"j\" is not in \"xyz\".'),
(215, 'python', 'Which of the following option is not a core data type in the python language?', 'Dictionary', 'Lists', 'Class', 'All of the above', 'C', 'Class is not a core data type because it is a user-defined data type. '),
(216, 'python', ' What happens when \"2\" == 2 is executed?', 'False', 'True', 'ValueError occurs', 'TypeError occurs', 'A', ' It only evaluates to false.'),
(217, 'python', 'Study the following statement<br>\r\nz = {\"x\":0, \"y\":1}  <br>\r\nWhich of the following is the correct statement?', 'x dictionary z is created', 'x and y are the keys of dictionary z', '0 and 1 are the values of dictionary z', 'All of the above', 'D', 'All of the above statements is correct regarding Python code');

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE `questions` (
  `id` int(11) NOT NULL,
  `course_name` varchar(255) DEFAULT NULL,
  `qualification` varchar(255) DEFAULT NULL,
  `level` int(11) NOT NULL,
  `year` int(11) NOT NULL,
  `question` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`id`, `course_name`, `qualification`, `level`, `year`, `question`) VALUES
(1, 'cpp', 'HND', 200, 2022, 'C++_PROGRAMMING_PAST_QUESTION (1).pdf'),
(2, 'cpp', 'HND', 200, 2021, 'C++_PROGRAMMING_PAST_QUESTION (2).pdf'),
(3, 'cpp', 'HND', 200, 2020, 'C++_PROGRAMMING_PAST_QUESTION (3).pdf'),
(4, 'cpp', 'HND', 200, 2023, 'C++_PROGRAMMING_PAST_QUESTION (4).pdf'),
(5, 'database', 'HND', 200, 2022, 'Database.pdf'),
(6, 'database', 'HND', 200, 2020, 'Database3.pdf'),
(7, 'database', 'HND', 200, 2019, 'Database4.pdf'),
(8, 'hci', 'HND', 200, 2021, 'hci21l200.pdf'),
(9, 'java', 'HND', 200, 2022, 'Java.pdf'),
(10, 'cpp', 'HND', 200, 2023, 'Cpp Resit 2023.pdf'),
(11, 'database', 'HND', 200, 2023, 'Database Resit 2023.pdf'),
(12, 'ecom', 'HND', 200, 2019, 'ecom1.pdf'),
(13, 'ecom', 'HND', 200, 2022, 'ecom2.pdf'),
(14, 'com. skills', 'HND', 200, 2023, 'comskills23dep.pdf'),
(15, 'com. skills', 'Btech', 100, 2023, 'comskills23btech.pdf'),
(16, 'com. skills', 'HND', 200, 2023, 'comskills23HND.pdf'),
(17, 'com. skills', 'HND', 100, 2023, 'comskills23dep.pdf');

-- --------------------------------------------------------

--
-- Table structure for table `students`
--

CREATE TABLE `students` (
  `id` int(11) NOT NULL,
  `fullName` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `registration_date` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `students`
--

INSERT INTO `students` (`id`, `fullName`, `email`, `password`, `registration_date`) VALUES
(1, 'Oppong Coffie', 'student1', 'student1', '2023-11-16 03:22:13'),
(2, 'Oppong Coffie', 'godblessme5011', '', '2023-11-30 10:58:11'),
(3, 'AA', 'A', 'A', '2023-12-10 19:44:05'),
(4, 'Bh', 'Ui', 'uu', '2023-12-10 20:20:44'),
(5, 'JamAGod ', 'yanksonpaa04@gmail.com', 'qwertyuiop', '2023-12-10 22:17:14');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `practice_questions`
--
ALTER TABLE `practice_questions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `questions`
--
ALTER TABLE `questions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `students`
--
ALTER TABLE `students`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `practice_questions`
--
ALTER TABLE `practice_questions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=218;

--
-- AUTO_INCREMENT for table `questions`
--
ALTER TABLE `questions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;

--
-- AUTO_INCREMENT for table `students`
--
ALTER TABLE `students`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
